# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_tasks: install-required-packages.yml
# now that the OpenJDK packages are installed, determine the location
# of the `javac` executable to use when setting the JAVA_HOME variable
# in our systemd service file
- name: Determine JAVA_HOME location
  shell: 'dirname "$(dirname "$(readlink -f "$(which javac)")")"'
  register: command_output
- set_fact: java_home='{{command_output.stdout}}'
- include_tasks: add-spark-user.yml
- include_tasks: install-apache-spark.yml
- include_role:
    name: configure-spark-nodes
- include_tasks: create-spark-service.yml
- include_tasks: start-spark-services.yml
