# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# create an initial version of the spark-defaults.conf file from the
# template in this role
- include: add-spark-defaults.yml static=no
# and add a log4j.properties file
- include: add-log4j-properties.yml static=no
# finally, if this is a multi-master play, then configure the target nodes of
# this play as a multi-master cluster that talk to each other through the
# external Zookeeper ensemble defined by the `zk_nodes` list
- include: configure-ha-cluster.yml static=no
  when: (zk_nodes | default([])) != [] and is_multi_master_play
